### ISSUE TITLE
Activity 103 Task 5 Error

### ISSUE THREAD

**Issue by meganwoodw** [STA518-02-Fall20/community#10]
I'm getting this error when I try to run the code at the last step and haven't been successful troubleshooting it.  Anybody else seeing this?
![image](https://user-images.githubusercontent.com/70483474/93006772-6fba4300-f52e-11ea-8f65-6f771792f2e1.png)

**Comment by dykesb** [comment]
This might be any issue still from Task 3 when you were fixing errors. Do you have an error in the `names(my_symbols)` chunk?

**Comment by meganwoodw** [comment]
Yes, that ended up being the problem. Thank you!
