### ISSUE TITLE
Activity 0103 Task 5 Problem

### ISSUE THREAD

**Issue by schrbren** [STA518-02-Fall20/community#11]
We had the same problem with the error message as another group in task 5 which is now resolved, however when running task 5 code the message is still not decoded. 

![Screen Shot 2020-09-13 at 3 31 15 PM](https://user-images.githubusercontent.com/70410911/93026763-5f5da300-f5d6-11ea-97b2-78af36c121c9.png)

We suspect this may be from the my_symbols dataframe, more specifically "assigning values in a new variable to Symbols":

![Screen Shot 2020-09-13 at 3 31 32 PM](https://user-images.githubusercontent.com/70410911/93026792-a51a6b80-f5d6-11ea-9364-6ba9634dd4e0.png)

Does this look correct? If not please help.

**Comment by dykesb** [comment]
`my_symbol` looks right. My guess is that it is your `top_secret`. The `NA` output leads me to think there aren't any matches.

**Comment by schrbren** [comment]
This is what our top_secret vector currently looks like: 

![Screen Shot 2020-09-13 at 3 57 50 PM](https://user-images.githubusercontent.com/70410911/93027305-01cb5580-f5da-11ea-9fe4-265f409bbc9d.png)

**Comment by dykesb** [comment]
When I try the first few entries of your vector, here is what I get:

```
> top_secret <- c(62, 31, 13, 10, 62, 12, 27, 20, 11, 62, 10, 17, 11, 62)
> stringr::str_c(my_symbols$Symbol[top_secret], collapse = "")
[1] "-Emj-lAtk-jqk-"
```

So it works for me, but that is not the correct message. My guess is some of your steps to create `top_secret` are not right causing future issues.

**Comment by ianfetterman** [comment]
I am having an issue getting task 5 as well but when my code runs it doesn't say NA, rather just doesn't give any output

![image](https://user-images.githubusercontent.com/70541521/93090680-1ad01700-f66b-11ea-9b23-8dda59701e68.png)
