### ISSUE TITLE
unable to pull merged activity because of committing .md file

### ISSUE THREAD

**Issue by steinaus** [STA518-02-Fall20/community#15]
Our team completed the pull requests and merge conflicts for activity 2.2, but when we went to pull the updated Rmd file into the main branch in RStudio, we came across an error that said:

"error: Your local changes to the following files would be overwritten by checkout: activty0202-data-summarization.md
Please commit your changes or stash them before you switch branches.
Aborting"

We realized, at this point, that the .md file had been altered in the main branch, and that one of us had accidentally staged the .md file along with the .Rmd file when knitting/committing/pushing the .Rmd file after completing one of the tasks. This caused the .md file to enter their branch (unlike how the instructions say the branches should only contain the .Rmd file). We believe that when we merged our branches, the .md file made it's way into the main branch, preventing us from making the final pull.

What is the best way to resolve this issue so that we can make our final pull/knit/commit/push?

**Comment by dykesb** [comment]
So I am understanding correctly, in RStudio when you are in your `main` branch and try to pull from GitHub you get this message? Or is it when, in RStudio you try to switch from your `username` branch to the `main` branch? The "...by checkout" leads me to think that this might be the issue - `checkout` what it is called when you switch between branches.

**Comment by steinaus** [comment]
The person who made the error gets the above message when trying to switch to the main branch. However, for me, I get the following message when trying to do the pull.

error: The following untracked working tree files would be overwritten by merge:
	activity0202-data-summarization.md
Please move or remove them before you merge.
Aborting

I tried to do the pull, and since it didn't work, the others made their own attempts. Sorry for the confusion.

**Comment by goochc** [comment]
So, it appears that each member of our group is experiencing different issues. But I was the one who accidentally knitted, committed, and pushed both the .rmd and .md files to my branch mid activity. Here is a screenshot of what I did on our repo 2.2 ("Completed task 5"):
 
![image](https://user-images.githubusercontent.com/29551685/93651726-80f8c900-f9e0-11ea-8ce1-05a869844945.png)

And when I try to switch branches in RStudio, I get the message stated in the beginning:
![image](https://user-images.githubusercontent.com/29551685/93651747-9a9a1080-f9e0-11ea-8f47-7629fd3b86ef.png)

**Comment by dykesb** [comment]
Ok, if you are the individual getting the "... by checkout" error, this means that you have made changes to a file on your `username` branch and the `main` branch also has changes that are different (e.g., you pushed an `.md` file from a different `username` branch). After verifying that you are in your `username` branch, you should do this in the **Terminal** (located in the lower-left-hand pane), pressing Enter/Return after each line:

```
git stash save your-full-file-name
git checkout main
```

Make whatever changes you want to in the `main` branch, stage/commit/push to `main`. Then, back in the **Terminal**:

```
git checkout staging
git stash pop
```

The above directions were adapted from this [StackOverflow answer](https://stackoverflow.com/a/22424970).

If you are the individual getting the "... by merge", verify that you are in the `main` branch and do this in the **Terminal**:

```
git fetch origin
git reset --hard origin/main
```

This will delete the current local `main` branch and overwrite with the GitHub version. This [StackOverflow answer](https://stackoverflow.com/a/1628334) was useful for this solution.
