### ISSUE TITLE
Starting Learning Targets

### ISSUE THREAD

**Issue by tagudarj** [STA518-02-Fall20/community#20]
For the Learning Targets, are we allowed to earn more than one "complete" in one meeting? For example, if I feel that Project 1 meets the criteria for 3 Learning Targets, would I be able to earn those 3 "completes" at once (after discussion)?

Also, can you explain or give an example to how "3. Create a Video" would be done? I understand that you will need to see our work, but wouldn't the work be on R Studio? And are we required to also have a meeting with you after we submit it?

Lastly, are we allowed to start working on these Learning Targets now?

Thanks in advance!

**Comment by dykesb** [comment]
> For the Learning Targets, are we allowed to earn more than one "complete" in one meeting? For example, if I feel that Project 1 meets the criteria for 3 Learning Targets, would I be able to earn those 3 "completes" at once (after discussion)?

If you are using work on a Project to satisfy multiple Learning Targets, I will still ask specific questions during our video conference for each of the individual Learning Targets. It is your responsibility to provide rationale for why you believe your work demonstrates proficiency and I will verify with additional related questions.
 
> Also, can you explain or give an example to how "3. Create a Video" would be done? I understand that you will need to see our work, but wouldn't the work be on R Studio? And are we required to also have a meeting with you after we submit it?

Creating a video submission will require you to also screen capture as you work (something that can be done using [Panopto](https://www.gvsu.edu/elearn/help/panopto-68.htm) software which is available to you all for free). This option of being assessed for Learning Targets is separate from Project and Application items. You would need to request a problem for a specific target, I would provide you with a time frame for completing this, and we would have a follow-up meeting to discuss your solution AND you would need to answer additional related questions. This process is similar to Option 2 ("Schedule an oral assessment") except recorded vs "live".
 
> Lastly, are we allowed to start working on these Learning Targets now?

You are welcome to work on any Learning Target that has been specified on a Project or an Application. However, it may take me some time (e.g., a day or two) to get a problem together for you.
