### ISSUE TITLE
Application 1: allowed resources

### ISSUE THREAD

**Issue by lapoinla** [STA518-02-Fall20/community#22]
In Application 1, you say  we can use "R4DS text, RStudio Primers, Team Activities, or function help documentation.” Does this include the RStudio cheatsheets (i.e. Visualization and Data Wrangling) provided by RStudio?

**Comment by dykesb** [comment]
I would consider the cheatsheets provided by [RStudio](https://rstudio.com/resources/cheatsheets/) as part of the text/Primers. Therefore, these would be allowed to use on Applications. I will make this explicit on future instructions.
