### ISSUE TITLE
Preparation 8: 'emo' package error

### ISSUE THREAD

**Issue by tagudarj** [STA518-02-Fall20/community#23]
This error pops up when I try to knit my file for Activity 4.1. It says "there is no package called 'emo'."

![image](https://user-images.githubusercontent.com/70492517/94344622-9e382380-ffee-11ea-97f5-fdf43bd6918c.png)

**Comment by dykesb** [comment]
I forgot to remove portions in the Rmd file that start with `r emo:ji(...) `. These should be before every To-Do (which should also be called Tasks). Double fail on my part, sorry.

You can solve this one of two ways:

1. In your **Console** type and press enter after each line: 

```
install.packages("devtools") 
devtools::install_github("hadley/emo") 
```

2. Delete each  `r emo:ji(...) ` portion in the Rmd file.
