### ISSUE TITLE
Prep 10: Knitting Error

### ISSUE THREAD

**Issue by tagudarj** [STA518-02-Fall20/community#24]
I'm having a hard time knitting my document for Activity 5.1. I put my team name and loaded the packages, but there is still an error. I ran the code chunk that uploads the london csv and there is also an error message for that.
![Data Chunk Error](https://user-images.githubusercontent.com/70492517/94874484-1acc6700-0420-11eb-8c80-280289df064e.png)

**Comment by dykesb** [comment]
Above that code chunk, it says:

> **Do not** remove the `eval = FALSE` portion of this code chunk as you will encounter unintended issues when knitting.

You should also not run the individual code components as earlier I say that:

> Unfortunately, RStudio Cloud will timeout when trying to download the raw data from the database.

@tagudarj please remove the second image and make this into its own post. As that is a different issue.

**Comment by lapoinla** [comment]
I'm having the same issue with knitting, and I kept the eval = FALSE 
<img width="1064" alt="Screen Shot 2020-10-02 at 9 59 01 AM" src="https://user-images.githubusercontent.com/70482784/94931704-12af0e80-0496-11eb-9299-97beac04ec1f.png">

**Comment by tagudarj** [comment]
> I'm having the same issue with knitting, and I kept the eval = FALSE
> <img alt="Screen Shot 2020-10-02 at 9 59 01 AM" width="1064" src="https://user-images.githubusercontent.com/70482784/94931704-12af0e80-0496-11eb-9299-97beac04ec1f.png">

I also kept "eval = FALSE" and I'm having this same issue.

**Comment by dykesb** [comment]
If you are looking for a solution related to `File img/kBxPqPx.jpg not found in resource path` see Issue #25
