### ISSUE TITLE
Prep 10: Knitting message: File img/kVxPqPx.jpg not found in resource path

### ISSUE THREAD

**Issue by tagudarj** [STA518-02-Fall20/community#25]
I have an overall knitting error after I changed my team name and loaded the packages. 

![Knitting Error](https://user-images.githubusercontent.com/70492517/94932549-3888e300-0497-11eb-8487-6969e0ac4765.png)

**Comment by dykesb** [comment]
On line 163 of the .Rmd file it currently says: `![Painless dates](img/kVxPqPx.jpg)`

Update this to be: `![Painless dates](README-img/kVxPqPx.jpg)`

**Comment by lapoinla** [comment]
Perfect, thank you!
