### ISSUE TITLE
0401 Pushing Issue

### ISSUE THREAD

**Issue by setsmar** [STA518-02-Fall20/community#27]
![rquestion2](https://user-images.githubusercontent.com/70547379/95128905-1ce83b80-0728-11eb-966d-275773552b9e.png)
After fixing the errors in the code it will not let me push. Also a whole bunch of "...joins-part1_files..." have appeared in the Git tab. I think I broke something.

**Comment by setsmar** [comment]
I tried "log origin/mybranch..HEAD" in the terminal already but no luck.

**Comment by dykesb** [comment]
In your **Git** pane, click on the blue-down-arrow to pull what is currently on GitHub.
