### ISSUE TITLE
Activity 5.2 - Sheen Green, Task 5 (Cannot remove ampersands and commas)

### ISSUE THREAD

**Issue by Ste-Drew** [STA518-02-Fall20/community#29]
@STA518-02-Fall20/sheen-green

The str_extract_all() argument ".+[&,].+" removes all but ampersands and commas.

If ".+[^&,].+" is used, ampersands and commas are not removed, and non-collaboration songs are added to the list.

If "[^&,]" is used, ampersands and commas are removed, all letters and spaces are individually extracted, and non-collaboration songs are added to the list.

If we use str_split(), we get the answer immediately. For str_extract_all(), we cannot determine the regular expression needed to remove ampersands and commas, keep names whole, and not add non-collaboration songs.

**Comment by dykesb** [comment]
I have `"[^,&]+"` for `str_extract_all()`.

> Match characters not (`^`) in the list `[,&]` as many times as needed (`+`).

I like this tool for exploring regex: https://regexr.com/

**Comment by Ste-Drew** [comment]
Thank you!
