### ISSUE TITLE
September 2 Session Agenda Items

### ISSUE THREAD

**Issue by dykesb** [STA518-02-Fall20/community#3]
As mentioned in the [syllabus](https://sta518.github.io/courses/course-policies/getting-help/#class-sessions), you can use this Issue to post items that you wish me to address "in-person" for the entire class. Any item posted **before 4 pm** on **September 2** will be added to my agenda (I will be closing this Issue and creating the next class session Issue at 4 pm).

You can always post individual items as a [new Issue](https://github.com/STA518-02-Fall20/community/issues) that you want to discuss with classmates. I might ask that some of the items you post here instead be a new, separate Issue. Also, I might recommend items posted as separate Issues be posted in these agendas.

**Comment by steinaus** [comment]
I saw that in the "My Grades" section on Blackboard there are daily learning journal entries like this:
lj-2020-08-31-entry
lj-2020-09-01-entry
lj-2020-09-02-entry
Are we supposed to have made entries in our learning journals outside of the task for Preparation 1?

**Comment by dykesb** [comment]
I will definitely talk about this to start off the class session!
