### ISSUE TITLE
File conflicts too complex

### ISSUE THREAD

**Issue by setsmar** [STA518-02-Fall20/community#30]
Hello,
I'm getting errors when trying to merge 0701 activity. I've had this error before- I've tried pushing without the data file but it still won't merge. 
Thanks!
![merge](https://user-images.githubusercontent.com/70547379/96411218-19d45d00-11b6-11eb-83fb-5d9bc43b56c8.png)

**Comment by dykesb** [comment]
I notice that you pushed your `.md` in addition to the `.Rmd` file. This will usually cause these type of issues (part of the reason why my instructions say to only push `.Rmd` files when pre-merge). Students have said that doing this in GitHub Desktop (there is a link at the bottom of your pull request) is pretty self-explanatory, but I would be happy to help you through that during my drop-in sessions or schedule a meeting with me.
