### ISSUE TITLE
Project 6 Task 4 Clarification

### ISSUE THREAD

**Issue by steinaus** [STA518-02-Fall20/community#35]
In task 4 of project 6, after creating the plot, it says:

"Suppose we're interested in making inference about the typical number of years of education that a person has completed and this is our representative sample. Is the mean a good statistic to use here to describe the typical value of **salary**? Why or why not?"

Where it says salary, should it say education?

**Comment by dykesb** [comment]
For this whole section it should say education. Sorry for the confusion!
