### ISSUE TITLE
Activity 103 task 4 question

### ISSUE THREAD

**Issue by Lolinthea** [STA518-02-Fall20/community#9]
Wondering if anyone might have a good resource/reference for these steps?  Thanks!

7. Subtract the "evens" vector from the first column of your secret message matrix.
8. Subtract 100 from all numbers 18-24th rows of the 3rd column.
9. Multiply all numbers in the 4th and 5th column by 2.

**Comment by dykesb** [comment]
In the [Programming Basics](https://rstudio.cloud/learn/primers/1.2) primer, you learned about extracting specific items using the square brackets (`[ ]`). For example, if you have a vector that is a sequence of number 1 to 10:

```
> vec <- 1:10
> vec

[1]  1  2  3  4  5  6  7  8  9 10
```

You could show the 2nd, 5th, and 8th values by doing:

```
> vec[c(2, 5, 8)]

[1] 2 5 8
```

In matrices, you can do something similar where you can specify the row, the column, or both. If you have a 2 rows x 5 columns matrix:

```
> mat <- matrix(vec, ncol = 5)
> mat

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
```

You can pull just the second column by doing:

```
> mat[ ,2]

[1] 3 4
```

or the first row by doing:

```
mat[1,]

[1] 1 3 5 7 9
```

If I wanted to subtract "1" from every value in the second column and replace that in my matrix, I could do:

```
> mat[ ,2] <- mat[ ,2] - 1
> mat

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    5    7    9
[2,]    2    3    6    8   10
```

If I wanted to subtract a vector `vec2 <- c(10, 8, 6, 4, 2)` from every value in the first row and replace that in my matrix, I could do:

```
> vec2 <- c(10, 8, 6, 4, 2)
> vec2

[1] 10  8  6  4  2

> mat[ 1,] <- mat[ 1,] - vec2
> mat

     [,1] [,2] [,3] [,4] [,5]
[1,]   -9   -6   -1    3    7
[2,]    2    3    6    8   10
```

That should help, but I can find some web resources if you'd like more examples.
